/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import persistencia.GestorArchivos;
import sensores.*;
import sistema.SistemaMonitoreo;

/**
 *
 * @author rodolfo
 */
public class Grafica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Grafica.class.getName());

    /**
     * Creates new form Grafica
     */
    
    private SistemaMonitoreo sistema = new SistemaMonitoreo();
    private ArrayList<Sensor> sensores = new ArrayList<>();
    private Sensor sensorSeleccionado = null;
    
    
    public Grafica() {
        initComponents();
        labelResultado.setText("");
        campoValor.setText("");
        
        SensorTemperatura st = new SensorTemperatura("SensorTemperatura1");
        sensores.add(st);
        sistema.agregarSensor(st);

        SensorNivel sn = new SensorNivel(10.0, "SensorNivel1");
        sensores.add(sn);
        sistema.agregarSensor(sn);

        SensorPresion sp = new SensorPresion("SensorPresion1");
        sensores.add(sp);
        sistema.agregarSensor(sp);
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Sensor s : sensores) {
            model.addElement(s.getNombre());
        }
        jList1.setModel(model);
        
        comboTipo.removeAllItems();
        comboTipo.addItem("SensorTemperatura");
        comboTipo.addItem("SensorNivel");
        comboTipo.addItem("SensorPresion");
        comboTipo.addItem("SensorCaudal");
        comboTipo.addItem("SensorProximidad");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        labelLed = new javax.swing.JLabel();
        labelBuzzer = new javax.swing.JLabel();
        labelVentilador = new javax.swing.JLabel();
        labelExtra = new javax.swing.JLabel();
        labelVolumen = new javax.swing.JLabel();
        campoMinutos = new javax.swing.JTextField();
        btnCalcularVolumen = new javax.swing.JButton();
        btndetectarBotella = new javax.swing.JButton();
        labelTipo = new javax.swing.JLabel();
        labelValorActual = new javax.swing.JLabel();
        labelEstado = new javax.swing.JLabel();
        btnActivarDesactivar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaHistorial = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        labelAgregarResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(200);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(this::jList1ValueChanged);
        jScrollPane1.setViewportView(jList1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        labelLed.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelLed.setText("Led");

        labelBuzzer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelBuzzer.setText("Buzzer");

        labelVentilador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVentilador.setText("Ventilador");

        labelExtra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelExtra.setText("Label extra");

        labelVolumen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelVolumen.setText("Volumen ");

        campoMinutos.setText("Minutos");
        campoMinutos.addActionListener(this::campoMinutosActionPerformed);

        btnCalcularVolumen.setText("Calcular Volumen");
        btnCalcularVolumen.addActionListener(this::btnCalcularVolumenActionPerformed);

        btndetectarBotella.setText("Detectar Botella");
        btndetectarBotella.addActionListener(this::btndetectarBotellaActionPerformed);

        labelTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipo.setText("Tipo de Sensor");

        labelValorActual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValorActual.setText("Valor actual");

        labelEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEstado.setText("Estado");

        btnActivarDesactivar.setText("Desactivar");
        btnActivarDesactivar.addActionListener(this::btnActivarDesactivarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelExtra)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelLed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBuzzer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelVentilador, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(labelVolumen))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalcularVolumen)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btndetectarBotella)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActivarDesactivar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorActual)
                            .addComponent(labelTipo)
                            .addComponent(labelEstado))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelTipo)
                .addGap(18, 18, 18)
                .addComponent(labelValorActual)
                .addGap(18, 18, 18)
                .addComponent(labelEstado)
                .addGap(27, 27, 27)
                .addComponent(labelLed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBuzzer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(labelExtra)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVolumen)
                    .addComponent(campoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcularVolumen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndetectarBotella)
                    .addComponent(btnActivarDesactivar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actuadores", jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("     Valor");

        campoValor.setText("jTextField1");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        labelResultado.setText("o");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnRegistrar)
                .addGap(32, 32, 32)
                .addComponent(labelResultado)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar)
                    .addComponent(labelResultado))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Leer Dato", jPanel2);

        areaHistorial.setColumns(20);
        areaHistorial.setRows(5);
        jScrollPane2.setViewportView(areaHistorial);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnActualizar)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnActualizar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial", jPanel3);

        jLabel2.setText("        Tipo de Sensor");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipo.addActionListener(this::comboTipoActionPerformed);

        jLabel3.setText("         Nombre");

        campoNombre.setText("Nombre sensor");
        campoNombre.addActionListener(this::campoNombreActionPerformed);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        labelAgregarResultado.setText("o");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnAgregar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(labelAgregarResultado)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(96, 96, 96)
                .addComponent(labelAgregarResultado)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel4);

        jSplitPane1.setRightComponent(jTabbedPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        if (sensorSeleccionado == null) {
            labelResultado.setText("Seleccioná un sensor primero.");
            return;
        }

        String texto = campoValor.getText().trim();
        if (texto.isEmpty()) {
            labelResultado.setText("Ingresá un valor.");
            return;
        }

        try {
            double valor = Double.parseDouble(texto);

            if (sensorSeleccionado instanceof SensorTemperatura st) {
                st.registrarTemperatura(valor);
            } else if (sensorSeleccionado instanceof SensorNivel sn) {
                sn.registrarNivel(valor);
            } else if (sensorSeleccionado instanceof SensorPresion sp) {
                sp.registrarPresion(valor);
            } else if (sensorSeleccionado instanceof SensorCaudal sc) {
                sc.registrarCaudal(valor);
            } else if (sensorSeleccionado instanceof SensorProximidad sp) {
                sp.detectarBotella();
            }

            sistema.evaluarSistema();
            actualizarPanelActuadores();
            labelResultado.setText("Valor registrado en " + sensorSeleccionado.getNombre());

        } catch (NumberFormatException e) {
            labelResultado.setText("Ingresá un número válido.");
        } catch (excepciones.SensorDesactivadoException e) {
            labelResultado.setText("El sensor está desactivado.");
        } catch (excepciones.ValorFueraDeRangoException e) {
            labelResultado.setText("Valor fuera de rango.");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        int idx = jList1.getSelectedIndex();
        if (idx >= 0) {
            sensorSeleccionado = sensores.get(idx);
            actualizarPanelActuadores();
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        areaHistorial.setText("");
        GestorArchivos gestor = new GestorArchivos();
        if (!gestor.existeArchivo("historial.txt")) {
            areaHistorial.setText("Sin eventos registrados.");
            return;
        }
        try {
            ArrayList<String> lineas = gestor.obtenerLineas("historial.txt");
            for (int i = lineas.size() - 1; i >= 0; i--) {
                areaHistorial.append(lineas.get(i) + "\n");
            }
        } catch (IOException e) {
            areaHistorial.setText("Error al leer historial.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String tipo = (String) comboTipo.getSelectedItem();
        String nombre = campoNombre.getText().trim();

        if (nombre.isEmpty()) {
            nombre = tipo + (sensores.size() + 1);
        }

        Sensor nuevo = switch (tipo) {
            case "SensorTemperatura" -> new SensorTemperatura(nombre);
            case "SensorNivel" -> new SensorNivel(10.0, nombre);
            case "SensorPresion" -> new SensorPresion(nombre);
            case "SensorCaudal" -> new SensorCaudal(nombre);
            case "SensorProximidad" -> new SensorProximidad(nombre);
            default -> null;
        };

        if (nuevo != null) {
            sensores.add(nuevo);
            sistema.agregarSensor(nuevo);

            DefaultListModel<String> model = (DefaultListModel<String>) jList1.getModel();
            model.addElement(nuevo.getNombre());

            campoNombre.setText("");
            labelAgregarResultado.setForeground(new java.awt.Color(0, 130, 0));
            labelAgregarResultado.setText(nombre + " agregado con éxito.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void campoMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMinutosActionPerformed

    private void btnCalcularVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularVolumenActionPerformed
        // TODO add your handling code here:
        if (sensorSeleccionado instanceof SensorCaudal sc) {
            try {
                double minutos = Double.parseDouble(campoMinutos.getText().trim());
                double volumen = sc.calcularVolumen(minutos);
                labelVolumen.setText("Volumen: " + volumen + " L");
            } catch (NumberFormatException e) {
                labelVolumen.setText("Ingresá un número válido.");
            }
        }
    }//GEN-LAST:event_btnCalcularVolumenActionPerformed

    private void btndetectarBotellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetectarBotellaActionPerformed
        // TODO add your handling code here:
        if (sensorSeleccionado instanceof SensorProximidad sp) {
            sp.detectarBotella();
            labelExtra.setText("Botellas detectadas: " + sp.getCantidadBotellasDetectadas());
}
    }//GEN-LAST:event_btndetectarBotellaActionPerformed

    private void btnActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarDesactivarActionPerformed
        // TODO add your handling code here:
        if (sensorSeleccionado == null) return;

        if (sensorSeleccionado.isActivo()) {
            sensorSeleccionado.desactivar();
            btnActivarDesactivar.setText("Activar");
        } else {
            sensorSeleccionado.activar();
            btnActivarDesactivar.setText("Desactivar");
        }
        actualizarPanelActuadores();
    }//GEN-LAST:event_btnActivarDesactivarActionPerformed
    private void actualizarPanelActuadores() {
        
        if (sensorSeleccionado.isActivo()) {
            btnActivarDesactivar.setText("Desactivar");
        } else {
            btnActivarDesactivar.setText("Activar");
        }
        
        labelTipo.setText("Tipo: " + sensorSeleccionado.getClass().getSimpleName());
        labelValorActual.setText("Valor actual: " + sensorSeleccionado.getValorActual() + " " + sensorSeleccionado.getUnidadMedida());
        labelEstado.setText("EstadoActual: "+sensorSeleccionado.obtenerEstado(sensorSeleccionado));
        if (sensorSeleccionado instanceof SensorTemperatura st) {
            labelExtra.setVisible(true);
            labelLed.setVisible(true);
            labelBuzzer.setVisible(true);
            labelVentilador.setVisible(true);
            btndetectarBotella.setVisible(false);
           
            labelLed.setText( st.getLed().ejecutar());
            labelBuzzer.setText(st.getBuzzer().ejecutar());
            labelVentilador.setText( st.getVentilador().ejecutar());
            labelVentilador.setVisible(true);
            labelExtra.setText("Promedio: " + st.calcularPromedio() + " °C");
            campoMinutos.setVisible(false);
            btnCalcularVolumen.setVisible(false);
            labelVolumen.setVisible(false);
        } else if (sensorSeleccionado instanceof SensorNivel sn) {
            labelExtra.setVisible(true);
            labelLed.setVisible(true);
            labelBuzzer.setVisible(true);
            btndetectarBotella.setVisible(false);
            
            
            labelLed.setText(sn.getLed().ejecutar());
            labelBuzzer.setText( sn.getBuzzer().ejecutar());
            labelVentilador.setVisible(false);
            labelExtra.setText("Nivel: " + sn.calcularPorcentaje() + "%");
            campoMinutos.setVisible(false);
            btnCalcularVolumen.setVisible(false);
            labelVolumen.setVisible(false);
        } else if (sensorSeleccionado instanceof SensorPresion sp) {
            labelExtra.setVisible(true);
            labelLed.setVisible(true);
            labelBuzzer.setVisible(true);
            btndetectarBotella.setVisible(false);
            
            
            labelLed.setText( sp.getLed().ejecutar());
            labelBuzzer.setText(sp.getBuzzer().ejecutar());
            labelVentilador.setVisible(false);
            labelExtra.setText("");
        }
        else if(sensorSeleccionado instanceof SensorProximidad spro){
            labelExtra.setVisible(true);
            labelLed.setVisible(true);
            labelBuzzer.setVisible(true);
            btndetectarBotella.setVisible(true);
            
            labelExtra.setText("Botellas detectadas: " + spro.getCantidadBotellasDetectadas());
            campoMinutos.setVisible(false);
            btnCalcularVolumen.setVisible(false);
            labelVolumen.setVisible(false);
        }
        else if(sensorSeleccionado instanceof SensorCaudal sc){
            labelExtra.setVisible(true);
            labelLed.setVisible(true);
            labelBuzzer.setVisible(true);
            btndetectarBotella.setVisible(false);
            
            labelExtra.setVisible(false);
            campoMinutos.setVisible(true);
            btnCalcularVolumen.setVisible(true);
            labelVolumen.setVisible(true);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Grafica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHistorial;
    private javax.swing.JButton btnActivarDesactivar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCalcularVolumen;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btndetectarBotella;
    private javax.swing.JTextField campoMinutos;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoValor;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAgregarResultado;
    private javax.swing.JLabel labelBuzzer;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelExtra;
    private javax.swing.JLabel labelLed;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelValorActual;
    private javax.swing.JLabel labelVentilador;
    private javax.swing.JLabel labelVolumen;
    // End of variables declaration//GEN-END:variables
}
